pizza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += staticfiles_urlpatterns()

pizzas/urls.py
from django.urls import path
from . import views

app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'), ## home page
    path('pizzas', views.pizzas, name='pizzas'), ## pizza page
    path('pizzas/<int:pizza_id>/', views.pizza,name="pizza"), ## drill down into each pizza to see toppings
    
    path('comment/<int:pizza_id>/', views.comment, name='comment'), ## comment under pizza
    path('edit_comment/<int:comment_id>/', views.edit_comment, name='edit_comment'), ## edit comments
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

pizzas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Pizza(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'Toppings' ## I actually don't need this since it defaults by adding an 's'
    
    def __str__(self):
        return self.name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'comments' ## I actually don't need this since it defaults by adding an 's'
    
    def __str__(self):
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

pizzas/forms.py
from django import forms

from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

pizzas/views.py
from django.shortcuts import render, redirect
from .models import Pizza, Topping, Comment
from .forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.

def index(request):
    """The home page for Pizzeria"""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas':pizzas}

    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    toppings = pizza.topping_set
    comments = pizza.comment_set
    context = {'pizza':pizza, 'toppings': toppings, 'comments':comments}

    return render(request, 'pizzas/pizza.html', context)

@login_required
def comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)
        
        if form.is_valid():
            comment = form.save(commit=False)
            comment.pizza = pizza
            if pizza.owner == request.user:
                comment.save()
                form.save()
                return redirect('pizzas:pizza', pizza_id=pizza_id)
            else:
                print("Unauthorized Access")
                raise Http404

    context = {'form': form, 'pizza':pizza}
    return render(request, 'pizzas/comment.html', context)

@login_required
def edit_comment(request, comment_id):
    """Edit an existing comment."""
    comment = Comment.objects.get(id=comment_id)
    pizza = comment.pizza

    if pizza.owner != request.user:
        print("Unauthorized Access")
        raise Http404

    if request.method != 'POST':
        form = CommentForm(instance=comment)
    else:
        form = CommentForm(instance=comment, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('pizzas:pizza', pizza_id=pizza.id)
    
    context = {'comment': comment, 'pizza':pizza, 'form':form}
    return render(request, 'pizzas/edit_comment.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process compelted form.
        form = UserCreationForm(data=request.POST)
    #username has the appropriate characters, the passwords match,
    # and the user isn't trying to do anythign malicous in their submission
        if form.is_valid():
        #The save() method returns the newly created user object,
        # which we assign to new_user/
            new_user = form.save()
        # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('pizzas:index')

# Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

pizzas/templates/pizzas/base.html
<link rel="stylesheet" href="/static/styles.css">

<p>
<a href="{% url 'pizzas:index' %}">Home Page</a>
<a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
{% if user.is_authenticated %}
    Hello, {{ user.username }}
    <a href="{% url 'users:logout' %}">Log out</a>
{% else %}
    <a href="{% url 'users:register' %}">Register</a>
    <a href="{% url 'users:login' %}">Log in</a>
{% endif %}
</p>

{% block content %}

{% endblock content %}

pizzas/templates/pizzas/comment.html
{% extends "pizzas/base.html" %}

{% block content %}

    <p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>
    
        <p>Comment on the pizza:</p>

        <form action ="{% url 'pizzas:comment' pizza.id %}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}

            <button name="submit">Comment</button>
        </form>
{% endblock content %}

pizzas/templates/pizzas/edit_comment.html
{% extends "pizzas/base.html" %}

{% block content %}

    <p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>

    <p>Edit Comment</p>

    <form action="{% url 'pizzas:edit_comment' comment.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save Changes</button>
    </form>

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block title %}My amazing Pizzeria{% endblock %}

{% block content %}

    <p>Welcome to the Pizzeria home page!</p>
    
{% endblock content%}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}

    <p>Pizza: {{ pizza }}</p>

    <ul>

        {% for topping in toppings.all %}
        <li>
            <p>{{ topping.name|linebreaks }}</p>
        </li>

        {% empty %}
        <li> 
            There are no toppings for this pizza. 
        </li>

        {% endfor %}
    </ul>

    <p>Comment Section: </p>

    <ul>
        {% for comment in comments.all %}
        <li>
            <p>{{ comment.date_added|date:'M d, Y H:i' }} </p>
            <p>{{ comment.text|linebreaks }}</p>
            <p>
                <a href="{% url 'pizzas:edit_comment' comment.id %}">Edit comment</a>
            </p>
        </li>
    
        {% empty %}
        <li> 
            There are no comments for this pizza. 
        </li>

        {% endfor %}
    </ul>
    
    <p>
        <a href="{% url 'pizzas:comment' pizza.id %}">Add a new comment</a>
    </p>
    
{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

    <p>Pizzas</p>

    <ul>
        {% for pizza in pizzas %}
            <li>
                <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
            </li>
        {% empty %}
            <li>
                No pizzas have been added yet.
            </li>
        {% endfor %}
    </ul>
    
{% endblock content %}